# 测试环境配置
environment: testing

# 继承基础配置
extends: base.yaml

# 测试环境特定配置
application_name: "Haiven-Test"
knowledge_pack_path: ${KNOWLEDGE_PACK_PATH}
enabled_providers: ${ENABLED_PROVIDERS}

default_models:
  chat: ${ENABLED_CHAT_MODEL}
  vision: ${ENABLED_VISION_MODEL}
  embeddings: ${ENABLED_EMBEDDINGS_MODEL}


# 数据库配置
database:
  host: "10.195.15.57"
  port: "5432"
  db_name: "requirement_agent"
  db_account: "a_appconnect"
  db_password: "Snc0VBlf2@Qy"